title: "BigBatDB: The Big Bat Database Project"
description: "A collaborative project to unify bat trait data collection"
email: bigbatdatabase@gmail.com

url: "https://bigbatdatabase.org"
baseurl: ""

markdown: kramdown
theme: minima

header_pages:
  - page: index.md
    title: Home
  - page: resources.md
    title: Other Resources
  - page: JoinUs.md
    title: Join Us & Find Other Experts
  - page: about.md
    title: The Team
